- Web/starter_project_barbies/components/blog/SelectBlogTag.tsx
- Web/starter_project_barbies/package-lock.json
- Web/starter_project_barbies/package.json
Add select tag component for blog post
- Figma Design : 
- implementation
> feat(web-barbies) : Add select blog tag component

- Web/starter_project_barbies/components/common/Pagination.tsx
Created the pagination component, please review.
> feat(web-barbies): Create pagination component

- Web/starter_project_iconics/styles/globals.css
- Web/starter_project_iconics/tailwind.config.js
I also i want to add configuration for font-sizes, do you think it's necessary to add them.
> feat(web-iconics): add configuration for font-styles

- Mobile/starter_project_dartsmiths/lib/core/utils/colors.dart
- Mobile/starter_project_dartsmiths/lib/core/utils/images.dart
- Mobile/starter_project_dartsmiths/lib/core/utils/ui_converter.dart
I have created two files one for setting image paths and one for our colors.
> Added constant image and colors file to track colors and images

- Mobile/starter_project_dark_knights/lib/core/utils/colors.dart
i have added the colors needed to the project
> Add the colors of the project 

- Web/starter_project_barbies/components/blog/LikeButton.tsx
Fixing blog post like icon 
- the issue of importing blog post like icon from "web-barbies.tsehayneh.blog-card" branch is fixed.
> Web barbies.tsehayneh.blog post card

- Mobile/starter_project_dartsmiths/lib/core/utils/images.dart
- Mobile/starter_project_dartsmiths/lib/features/article/presentation/screens/article_page.dart
- Mobile/starter_project_dartsmiths/lib/features/article/presentation/widgets/article_profile.dart
- Mobile/starter_project_dartsmiths/lib/features/article/presentation/widgets/like_button.dart
I have recently added a new feature to the Articles section - an article reading page! Check out the screenshot below to see what it looks like
> feat(dartsmiths) Created article reading page

- Mobile/starter_project_dark_knights/lib/features/write_article/presentation/screen/write_article_page.dart
- Mobile/starter_project_dark_knights/lib/features/write_article/presentation/widgets/add_article_content.dart
- Mobile/starter_project_dark_knights/lib/features/write_article/presentation/widgets/add_tags.dart
- Mobile/starter_project_dark_knights/lib/features/write_article/presentation/widgets/publish_button.dart
- Mobile/starter_project_dark_knights/lib/features/write_article/presentation/widgets/text_fields.dart
- Mobile/starter_project_dark_knights/lib/features/write_article/presentation/widgets/title_bar.dart
**Team:** Mobile
**Team Name:** Dartknights
**Task Name:** Implement Write article page
**Task Description:** Implement Write article page which enables the user to add and remove multiple tags into the UI
**Screenshot:**
> feat(mobile-dart-knights) : implement write article page

- Web/starter_project_vanguard/components/success-story/Partners.tsx
- Web/starter_project_vanguard/components/success-story/SuccessImageCard.tsx
- Web/starter_project_vanguard/pages/success-story/index.tsx
I've made some changes to the code to improve the page responsiveness. Specifically, I replaced "img" with "Image" for better accessibility, and I also made some adjustments to the layout to ensure that the page displays properly on different screen sizes.
> img->Image

- Web/starter_project_iconics/components/story/GlassImage.tsx
- Web/starter_project_iconics/components/story/PartnersLogos.tsx
> use next/image

- Web/starter_project_vanguard/components/teams/HeroSection.tsx
- Web/starter_project_vanguard/components/teams/MemberCard.tsx
- Web/starter_project_vanguard/data/success-story.json
> fix(web-vanguard): make the hero on teams page responsive

- Web/starter_project_iconics/styles/globals.css
remove empty teams page
remove body background
> fix(web-iconics): remove extra teams page

- Mobile/starter_project_matador/lib/features/login/Presentation/screen/login_page.dart
- Mobile/starter_project_matador/lib/features/login/Presentation/widgets/forgot_password.dart
- Mobile/starter_project_matador/lib/features/login/Presentation/widgets/input_form_field.dart
- Mobile/starter_project_matador/lib/features/login/Presentation/widgets/login_signup.dart
- Mobile/starter_project_matador/lib/features/login/Presentation/widgets/logo.dart
- Mobile/starter_project_matador/lib/features/login/Presentation/widgets/rounded_button.dart
- Mobile/starter_project_matador/lib/features/login/Presentation/widgets/sign_in_with_your_account.dart
fix(matador.joshua): add forget password
- older: forgot_password widget was left out by .gitignore
- fix: forgot_password widget pushed
> fix(matador.joshua): add forget password

- Web/starter_project_barbies/components/layout/Navbar.tsx
Creating a pull request for the updated navbar
> A navbar on the new branch

- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Application.UnitTest/Ratetest/Command/CreateRateCommandHandlerTest.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Application.UnitTest/Ratetest/Command/DeleteRateCommandHandlerTest.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Application.UnitTest/Ratetest/Command/UpdateRateCommandHandlerTest.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Application.UnitTest/Ratetest/Query/GetRateDetailQueryHandlerTest.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Application.UnitTest/Ratetest/Query/GetRateListQueryHandlerTest.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Application/Features/Rates/CQRS/Handlers/DeleteRateCommandHandler.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp2.sln
This Pull request is not to add new things. It is to fix minor bugs in some files.  And renaming of  Rate test folder in the application test project to follow best practices.
> Gadisa.rate crud fix

- Web/starter_project_iconics/components/home/SuccessCard.tsx
- Web/starter_project_iconics/components/home/SuccessRate.tsx
- Web/starter_project_iconics/data/home/success-rate.ts
- Web/starter_project_iconics/pages/index.tsx
- Web/starter_project_iconics/types/home/success-rate.tsx
Worked on the success-rate section of the homepage.
> feat(web-iconics): implement success-rate section of the homepage

- Mobile/starter_project_matador/lib/core/utils/constants/colors.dart
- Mobile/starter_project_matador/lib/core/utils/constants/styles.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/screen/signup_page.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/widgets/data_fill.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/widgets/input_box.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/widgets/login_text_at_the _end.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/widgets/logo.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/widgets/signup_and_signin_box.dart
- Mobile/starter_project_matador/lib/features/signup/presentation/widgets/signup_button.dart
A typical signup page using Flutter would have a clean and simple UI/UX design that prioritizes ease of use and accessibility. The page would likely include a prominent header with a logo or branding, as well as clear and concise instructions for creating an account.
The signup form itself would be straightforward and intuitive, with fields for entering basic user information such as name, email address, and password. The form may also include optional fields for additional information, such as a profile picture or bio.
To ensure a smooth and seamless experience for users, the signup page may include features such as real-time validation of form fields, error messaging for any incorrect or missing information, and the ability to save progress and return to the form later if needed. …
> feat( metador/signup_page ) ui/ux

- Mobile/starter_project_dark_knights/lib/core/utils/colors.dart
- Mobile/starter_project_dark_knights/lib/features/article/presentation/widgets/title_bar.dart
Fix errors which are occurred due to undefined colors and text styles.
> fix(mobile-dart-knights): fix color and style errors.

- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.API/Controllers/BlogsController.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.API/Program.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.API/appsettings.json
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Contracts/Persistence/IUnitOfWork.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/CQRS/Handlers/Commands/CreateBlogCommandHandler.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/CQRS/Handlers/Commands/DeleteBlogCommandHandler.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/CQRS/Handlers/Commands/UpdateBlogCommandHandler.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/CQRS/Handlers/Queries/GetBlogListQueryHandler.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/CQRS/Requests/Commands/UpdateBlogCommand.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/CQRS/Requests/Queries/GetBlogListQuery.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/DTOs/BlogListDto.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/DTOs/UpdateBlogDto.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Features/Blog/DTOs/Validators/UpdateBlogDtoValidator.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Application/Profiles/MappingProfile.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Persistence/BlogAppDbContext.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Persistence/Repositories/BlogRepository.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Persistence/Repositories/UnitOfWork.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Tests/Blog/Command/DeleteBlogCommandHandler.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Tests/Blog/Command/UpdateBlogCommandHandlerTest.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Tests/Blog/Query/GetBlogListQueryTest.cs
- Backend/starter_project_zsilentcoders/BlogApp3/BlogApp.Tests/Mocks/MockUnitOfWork.cs
This PR includes addition of the update and get operations for the blog model, it also includes the test for these operations as well.
> feat(backend-zsilentcoders): implement blog CRUD

- Web/starter_project_barbies/components/blog/BlogCard.tsx
Fix single blog route 
- fixing single blog route when a user clicks a read more button
> fix(we-barbies) : Fix single blog route

- Mobile/starter_project_dark_knights/lib/features/article/domain/entities/article.dart
- Mobile/starter_project_dark_knights/pubspec.yaml
- Mobile/starter_project_dark_knights/test/features/article/domain/usecases/delete_article_test.dart
- Mobile/starter_project_dark_knights/test/features/article/domain/usecases/get_articles_by_id_test.dart
- Mobile/starter_project_dark_knights/test/features/article/domain/usecases/get_articles_by_user_id_test.dart
- Mobile/starter_project_dark_knights/test/features/article/domain/usecases/get_articles_test.dart
- Mobile/starter_project_dark_knights/test/features/article/domain/usecases/post_article_test.dart
- Mobile/starter_project_dark_knights/test/features/article/domain/usecases/update_article_test.dart
This PR fix's the type error on tag attribute of Article entity
- Changed the type for tag attribute on Article entity
- changed the same thing on each usecase tests.
> fix(mobile-dark_knight): fix tag type error on article entity

- Mobile/starter_project_dark_knights/lib/features/user_profile/data/models/user_model.dart
- Mobile/starter_project_dark_knights/test/features/user_profile/data/models/user_model_test.dart
- Mobile/starter_project_dark_knights/test/fixtures/fixture_reader.dart
- Mobile/starter_project_dark_knights/test/fixtures/user.json
Team: Mobile
Team name: Dartknights
Task Name: Create user model
description: Create user model that extends the user entity from the domain layer with the tests included.
> feat(Mobile-Dartknights): Create user model with tests

- Mobile/starter_project_dark_knights/lib/features/user_profile/domain/usecases/get_followers.dart
- Mobile/starter_project_dark_knights/lib/features/user_profile/domain/usecases/get_number_of_following.dart
- Mobile/starter_project_dark_knights/lib/features/user_profile/domain/usecases/get_user.dart
- Mobile/starter_project_dark_knights/test/features/user_profile/domain/usecases/get_followers_test.dart
- Mobile/starter_project_dark_knights/test/features/user_profile/domain/usecases/get_number_of_following_test.dart
- Mobile/starter_project_dark_knights/test/features/user_profile/domain/usecases/get_user_test.dart
I have implemented and tested the tasks on the jira issue (userEntity ,userRepository ,getUser,getNumberOfFollowing and getFollowers usecases).
> feat(mobile:dart_knights):user-domain-layer

- Mobile/starter_project_dark_knights/android/local.properties
- Mobile/starter_project_dark_knights/lib/features/Authentication/data/models/authentication.dart
- Mobile/starter_project_dark_knights/lib/features/Authentication/domain/entities/authentication_entitiy.dart
- Mobile/starter_project_dark_knights/lib/features/Authentication/domain/usecases/loginUsecase.dart
- Mobile/starter_project_dark_knights/lib/features/Authentication/domain/usecases/signupUsecase.dart
- Mobile/starter_project_dark_knights/test/features/authentication/data/models/authentication_model_test.dart
- Mobile/starter_project_dark_knights/test/fixtures/authentication_valid.json
- Mobile/starter_project_dark_knights/test/fixtures/fixure_reader.dart
Team: mobile
Team Name : dartknight
task : implement authentication model
task description:This PR implements an authentication model that includes both login and sign-up use cases.and  tests it using a JSON file in the fixture directory.
> feat(mobile-dartknight)implement authentication model 

- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Domain/BlogUser.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Persistence/BlogAppDbContext.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Persistence/BlogAppDbContextFactory.cs
- Backend/starter_project_dotnetforce7/BlogApp2/BlogApp.Persistence/Repositories/BlogRepository.cs
In this pr, we created a new user model the BlogAppDbContext could access and made sure every time a new user is created in the identity user it's also propagated to the new user(BlogUser) table.
We've also created the relation users should have with blog. For the other models we should follow the same steps we followed to create relations.
> feat(backend-dotnetfroces7): Add new user in blog and link user with blog

- Web/starter_project_iconics/components/teams/TeamMembersList.tsx
- Web/starter_project_iconics/data/teams/team-members.json
add pagination to team members list
> fix(web-iconics): add pagination to team members list

- Mobile/starter_project_matador/lib/core/error/exceptions.dart
- Mobile/starter_project_matador/lib/core/error/failures.dart
- Mobile/starter_project_matador/lib/core/network/network_info.dart
- Mobile/starter_project_matador/lib/features/user/data/datasources/user_local_data_source.dart
- Mobile/starter_project_matador/lib/features/user/data/datasources/user_remote_data_source.dart
- Mobile/starter_project_matador/lib/features/user/data/models/user_model.dart
- Mobile/starter_project_matador/lib/features/user/data/repositories/user_repository_imp.dart
- Mobile/starter_project_matador/lib/features/user/domain/entities/user.dart
- Mobile/starter_project_matador/lib/features/user/domain/repositories/user_repository.dart
- Mobile/starter_project_matador/lib/features/user/domain/usecases/add_user.dart
- Mobile/starter_project_matador/lib/features/user/domain/usecases/delete_user_by_id.dart
- Mobile/starter_project_matador/lib/features/user/domain/usecases/edit_user_by_id.dart
- Mobile/starter_project_matador/lib/features/user/presentation/bloc/user_bloc.dart
- Mobile/starter_project_matador/lib/features/user/presentation/bloc/user_event.dart
- Mobile/starter_project_matador/lib/features/user/presentation/bloc/user_state.dart
- Mobile/starter_project_matador/pubspec.yaml
- Mobile/starter_project_matador/test/features/user/data/models/user_model_test.dart
**Description**
This pull request adds a user data layer to the project, along with a corresponding bloc in the presentation layer. The data layer includes a contract and implementation for a user data source, as well as a repository implementation that provides a single point of access to the data source. The user model is also included in the data layer.
The presentation layer includes a bloc that manages the state of the user data and emits state changes based on events triggered by the UI. The bloc is implemented using the Bloc library, and includes separate state and event classes. The bloc emits states based on the events received, allowing the UI to react to changes in the user data.
**Changes Made**
- Added a user data layer with a contract and implementation for a user data …
> Mobile.duressa jemal.user.data layer and bloc

- Mobile/starter_project_dark_knights/lib/features/user_profile/presentation/bloc/user_profile_bloc.dart
- Mobile/starter_project_dark_knights/lib/features/user_profile/presentation/bloc/user_profile_event.dart
- Mobile/starter_project_dark_knights/lib/features/user_profile/presentation/bloc/user_profile_state.dart
I have implemented the Bloc logic for the user profile.
> feat(mobile: dark_knights): User Profile Bloc

- Mobile/starter_project_matador/lib/features/article/data/datasources/article_local_data_source.dart
- Mobile/starter_project_matador/lib/features/article/data/datasources/article_remote_data_source.dart
- Mobile/starter_project_matador/lib/features/article/data/models/article_model.dart
- Mobile/starter_project_matador/lib/features/article/data/repositories/article_repository_impl.dart
- Mobile/starter_project_matador/lib/features/article/domain/entities/article.dart
- Mobile/starter_project_matador/lib/features/article/presentation/bloc/article_bloc.dart
- Mobile/starter_project_matador/lib/features/article/presentation/bloc/article_event.dart
- Mobile/starter_project_matador/lib/features/article/presentation/bloc/article_state.dart
- Mobile/starter_project_matador/pubspec.yaml
Changes:
-[x] Added error handling and logging.
-[x] Updated relevant documentation.
-[x] Added unit and integration tests.
Please review and provide feedback.
> fix(matador.seid) :adding the datasource implementation

- Mobile/starter_project_dark_knights/lib/article_injection.dart
- Mobile/starter_project_dark_knights/pubspec.yaml
This pull request adds the dependency injection for article feature
- Added article_dependency_Injection.dart file
> implement dependency injection for article feature

- Mobile/starter_project_dark_knights/lib/features/feeds/presentation/bloc/feed_bloc.dart
- Mobile/starter_project_dark_knights/lib/features/feeds/presentation/bloc/feed_event.dart
- Mobile/starter_project_dark_knights/lib/features/feeds/presentation/bloc/feed_state.dart
implemented the bloc of feed feature:
- created the state of feed
- implemented the events of feed
- implemented the bloc of feed
> feat(mobile : Dart Knight) implement the bloc of feed

- Web/starter_project_barbies/components/blog/BlogCard.tsx
- Web/starter_project_barbies/pages/blogs/my-blogs/edit-blog/[blog-id].tsx
- Web/starter_project_barbies/store/blog/blogs-api.ts
- Web/starter_project_barbies/types/blog.ts
implemented UI and Integration for edit blog functionality
> feat(web-barbies): implement edit blog UI and Integration

- Mobile/starter_project_dark_knights/lib/features/feeds/presentation/bloc/feed_bloc.dart
- Mobile/starter_project_dark_knights/lib/features/feeds/presentation/bloc/feed_event.dart
- Mobile/starter_project_dark_knights/lib/features/feeds/presentation/bloc/feed_state.dart
there was no load article by id implementation on my previous merge so this pr is to add that.
> feat(mobile: Dart knight) : added loadarticle by id on feed bloc

- Mobile/starter_project_matador/lib/features/article/data/datasources/article_remote_data_source.dart
- Mobile/starter_project_matador/lib/features/article/data/models/article_model.dart
- Mobile/starter_project_matador/lib/features/article/data/repositories/article_repository_impl.dart
- Mobile/starter_project_matador/lib/features/article/domain/repositories/article_repository.dart
- Mobile/starter_project_matador/lib/features/article/domain/usecases/get_all_articles.dart
- Mobile/starter_project_matador/lib/features/article/domain/usecases/get_article_by_id.dart
- Mobile/starter_project_matador/lib/features/article/domain/usecases/get_list_of_article.dart
- Mobile/starter_project_matador/lib/features/article/presentation/bloc/article_bloc.dart
- Mobile/starter_project_matador/lib/features/article/presentation/screen/article_reading.dart
- Mobile/starter_project_matador/lib/features/feed/presentation/block/feed_bloc.dart
- Mobile/starter_project_matador/lib/features/feed/presentation/block/feed_event.dart
- Mobile/starter_project_matador/lib/features/feed/presentation/block/feed_state.dart
- Mobile/starter_project_matador/lib/features/feed/presentation/screen/home_page.dart
- Mobile/starter_project_matador/lib/features/feed/presentation/widgets/article_preview_card.dart
- Mobile/starter_project_matador/lib/features/feed/presentation/widgets/home_page_body.dart
- Mobile/starter_project_matador/lib/injection/injection.dart
- Mobile/starter_project_matador/lib/main.dart
- Mobile/starter_project_matador/pubspec.yaml
Description
This pull request adds bloc consumption for the feed feature, including the implementation of the repository and data source for article feature.
> Mobile.duressaJemal.homepage.feed-bloc

- Web/starter_project_vanguard/components/blog/BlogCard.tsx
- Web/starter_project_vanguard/components/profile/MyBlogs.tsx
> To the blog card, add a delete and update button. The buttons are only visible for blogs created by the user (only for the myblog component).
> Update Json file: change _id to id
> Jebessa.update blog card

- Mobile/starter_project_dark_knights/lib/article_injection.dart
- Mobile/starter_project_dark_knights/lib/article_injection_container.dart
- Mobile/starter_project_dark_knights/lib/feed_injection_container.dart
- Mobile/starter_project_dark_knights/lib/injection_container.dart
- Mobile/starter_project_dark_knights/lib/main.dart
- Mobile/starter_project_dark_knights/lib/user_injection_container.dart
Team: Mobile
Team Name: Dartknights
Task Name: Implement dependency injection
Task Description: Implement the injection_container.dart file that call other feature specific dependency files and call it in the main app.
> (Mobile-Dartknights): Add dependency injection file that wraps all other dependency files.
